-keep public class * extends android.app.Activity
-keep class org.stenerud.kscrash.init.* { *; }
-keep class org.stenerud.kscrash.KSCrash { *; }
-keep interface org.stenerud.kscrash.IDealWithCrash { *;}
